Updated: using jq instead of JSON.awk

diff --git a/spotify-album-export b/spotify-album-export
--- a/spotify-album-export
+++ b/spotify-album-export
@@ -17,16 +17,16 @@
 # a simple album list. All with one simple command.
 
 # The final format of the album list file will be:
-#   artist|album|spotify_uri
-#   artist|album|spotify_uri
+#   artist|album_title|album_id
+#   artist|album_title|album_id
 #   ...and so on
 
 # Then you can process this file as you wish, for example
 # you can pipe it to dmenu with a script (like spotymenu).
 
-# Acknowledgement
-# This script uses JSON.awk to format the exported json file.
-# JSON.awk was written by step: https://github.com/step-/JSON.awk
+# Dependecy: jq
+# Should be in your repositories. Or you can get it from here:
+# https://stedolan.github.io/jq/
 
 # Related Spotify Documentation:
 # https://developer.spotify.com/web-api/get-users-saved-albums/
@@ -43,33 +43,29 @@
 # The maximum number of objects to return. Default: 20. Minimum: 1. Maximum: 50.
 limit="50" # use the max
 
-# Set the file paths
-file_extracted_json=/tmp/spotify_exported_album_list.json
-file_albumlist=~/spoty_albums
-file_json_awk=~/Scripts/JSON.awk
+# Album list saved to this file
+file_albumlist=~/spotify_exported_album_list
 
 # -----------------
 # --- Functions ---
 # -----------------
 
-error_json_awk() {
-    echo "Error: cannot find $file_json_awk"
-    echo "You need to set the correct path for the file_json_awk variable in the script."
+dep_check() {
+    if [[ ! -x /bin/jq ]]; then
+        echo "Error: can't find 'jq'. Make sure you have it installed! https://stedolan.github.io/jq/"
+        exit 1
+    fi
 }
 
 get_album_list() {
+
     if [[ -z $token ]]; then
         echo -e "Error: you need to specify a token!\n"
         usage
         exit 1
     fi
 
-    if [[ -f "$file_json_awk" ]];then
-        curl --silent -X GET "https://api.spotify.com/v1/me/albums?limit=$limit" -H "Accept: application/json" -H "Authorization: Bearer $token" > $file_extracted_json && echo -e "$file_extracted_json" | awk -f "$file_json_awk" | awk -F']' '/^\["items",[0-9]{1,2},"album","artists",0,"name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"} /^\["items",[0-9]{1,2},"album","name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"} /^\["items",[0-9]{1,2},"album","id"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2}' | sed -n 'p;n;h;n;G;p' | sed '$!N;$!N;s/\n//g' >> $file_albumlist && echo "Done. You can find the album list here: $file_albumlist"
-    else
-        error_json_awk
-        exit 1
-    fi
+    curl --silent -X GET "https://api.spotify.com/v1/me/albums?limit=$limit" -H "Accept: application/json" -H "Authorization: Bearer $token" | jq -r '.items | map([.album.artists[].name, .album.name, .album.id] | join("|")) | join("\n")' >> $file_albumlist && echo "Done. You can find the album list here: $file_albumlist"
 }
 
 get_album_list_with_offset() {
@@ -79,13 +75,8 @@ get_album_list_with_offset() {
         exit 1
     fi
 
-    if [[ -f "$file_json_awk" ]];then
-        curl --silent -X GET "https://api.spotify.com/v1/me/albums?offset=$offset&limit=$limit" -H "Accept: application/json" -H "Authorization: Bearer $token" > $file_extracted_json && echo -e "$file_extracted_json" | awk -f "$file_json_awk" | awk -F']' '/^\["items",[0-9]{1,2},"album","artists",0,"name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"} /^\["items",[0-9]{1,2},"album","name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"} /^\["items",[0-9]{1,2},"album","id"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2}' | sed -n 'p;n;h;n;G;p' | sed '$!N;$!N;s/\n//g' >> $file_albumlist && echo "Done. You can find the album list here: $file_albumlist"
+        curl --silent -X GET "https://api.spotify.com/v1/me/albums?offset=$offset&limit=$limit" -H "Authorization: Bearer $token" | jq -r '.items | map([.album.artists[].name, .album.name, .album.id] | join("|")) | join("\n")' >> $file_albumlist && echo "Done. You can find the album list here: $file_albumlist"
 
-    else
-        error_json_awk
-        exit 1
-    fi
 }
 
 add_by_uri(){
@@ -96,18 +87,19 @@ add_by_uri(){
     fi
 
     album_id=$(echo "$uri" | awk -F ':' '{print $3}')
-    curl --silent -X GET "https://api.spotify.com/v1/albums/$album_id" > $file_extracted_json && echo -e "$file_extracted_json" | awk -f "$file_json_awk" | awk -F']' -v album_id="$album_id" '/^\["artists",[0-9]{1,2},"name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"} /^\["name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"album_id}' | sed '$!N;$!N;s/\n//g' >> $file_albumlist && echo "Done. You can find the album list here: $file_albumlist"
+    curl --silent -X GET "https://api.spotify.com/v1/albums/$album_id" | jq -r '. | [.artists[].name, .name, .id] | join("|")' >> $file_albumlist && echo "Done. You can find the album list here: $file_albumlist"
 }
 
 usage() {
     echo -e "Usage: $(basename $0) [option] [token]\n"
+    echo "Without an option it will export the first 50 albums. This is the maximum that Spotify allows on a single run."
+    echo -e "Use 50 as an offset on the second run, then 100 on the third run an so on...\n"
     echo "You can get your personal token here (after logged in to spotify):"
-    echo -e "https://developer.spotify.com/web-api/console/get-current-user-saved-albums/\n"
+    echo "https://developer.spotify.com/web-api/console/get-current-user-saved-albums/"
+    echo -e "Check the 'user-library-read' option.\n"
     echo "Options:"
     echo "              -o <offset> <token>     Offset number: begin the extraction from here. You have to specify the token after it."
     echo "              -a <uri>                Add album to the album list by a spotify_uri (e.g.: spotify:album:41bTjcSaiEe4G40RVVHbux)"
-    echo "                                      In this script the default limit is 50 so you might want to use '-o 50' to get the next 50 on the second run,"
-    echo "                                      then '-o 100' on the third run and so on)."
     echo "              -h                      This help page."
 }
 
@@ -116,8 +108,8 @@ usage() {
 # ----------------------
 
 case "$1" in
-    -o) offset="$2" token="$3" get_album_list_with_offset;;
-    -a) uri="$2" add_by_uri;;
+    -o) dep_check && offset="$2" token="$3" get_album_list_with_offset;;
+    -a) dep_check && uri="$2" add_by_uri;;
     -h) usage;;
-    *) token="$1" get_album_list;;
+    *) dep_check && token="$1" get_album_list;;
 esac
